"""Callback functions for the Root‑MAS platform.

Callbacks are used to intercept events during the execution of the MAS and
perform side effects such as sending messages to external services.  This
module provides a stub implementation of the `outgoing_to_telegram` callback
used by the Communicator agent.
"""

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


def outgoing_to_telegram(message: Dict[str, Any]) -> None:
    """Forward assistant messages to the Telegram bot.

    This callback is triggered whenever the MAS produces an assistant message.
    It should extract the textual content, optionally convert it to speech via
    the SpeechKitClient and send it through the Communicator's bot.  In this
    skeleton implementation the function simply logs the event.

    Args:
        message: The message object generated by the MAS.  It is expected to
            contain at least a `content` field with the assistant's reply.
    """
    content = message.get("content", "")
    logger.info("Outgoing message to Telegram: %s", content)
    # TODO: retrieve Communicator instance and call its send method
    # e.g. communicator.send_text(content) or communicator.send_voice(audio_bytes)
    raise NotImplementedError("Outgoing Telegram callback not implemented")