## Описание корневых агентов
#
# Для каждого агента указывается роль, название модели по умолчанию,
# fallback‑политика и используемая память. Эти значения являются
# ориентировочными: вы можете менять их в соответствии с реальными
# потребностями и поддерживаемыми LLM.

agents:
  # Отвечает за постановку целей, бюджет и дедлайны
  meta:
    role: "Понимает цели, деньги, дедлайны"
    model: "premium"  # первичный tier, fallback на standard прописывается в llm_tiers.yaml
    memory: "global+local"

  # Управляет очередями задач, статусами и cron‑процессами
  coordination:
    role: "Очереди, статусы, cron"
    model: "cheap"
    memory: "global"

  # Создаёт и аудирует промпты, хранит best‑practice
  prompt_builder:
    role: "Пишет и аудирует промпты"
    model: "standard"
    memory: "prompt_best_practice"

  # Выбирает подходящие LLM по рейтингу
  model_selector:
    role: "Выбирает модели по рейтингу"
    model: "cheap"
    memory: "models_kb"

  # Создаёт агентов и MAS инстансы
  agent_builder:
    role: "Создаёт агенты по спецификации"
    model: "standard"
    memory: null

  # Развёртывает internal и client MAS
  instance_factory:
    role: "Развёртывает MAS инстансы"
    model: "cheap"
    memory: "instances_db"

  # Выполняет web‑поиск и поиск по API с использованием RAG
  researcher:
    role: "Проводит исследования (web/API)"
    model: "premium"
    memory: "research_mem"

  # Валидирует факты и источники
  fact_checker:
    role: "Проверяет источники"
    model: "cheap"
    memory: null

  # Выполняет вызовы внешних API
  multitool:
    role: "LLM‑вызовы внешних API"
    model: "fixed"
    memory: null

  # Генерирует JSON для workflow n8n
  wf_builder:
    role: "Генерирует n8n workflow"
    model: "standard"
    memory: "wf_recipes"

  # Интегрируется с GPT‑Pilot для создания приложений
  webapp_builder:
    role: "Запускает GPT‑Pilot"
    model: "standard"
    memory: null

  # Отвечает за коммуникацию с пользователем через Telegram, STT/TTS
  communicator:
    role: "Телеграм‑интерфейс (STT/TTS)"
    model: "ya_gpt"
    memory: "chat_mem"
