# Definitions of core agents for the Root‑MAS platform.
# Each agent entry contains a brief description, the preferred LLM tier and notes
# about the type of memory it uses.  These definitions are for documentation
# purposes and to drive future configuration logic.

agents:
  meta:
    role: Meta
    description: >-
      Understands high‑level goals, budgets and deadlines.  Responsible for
      orchestrating work across other agents and ensuring that business
      objectives are met.  Falls back from premium to standard models.
    default_tier: premium
    memory: global

  coordination:
    role: Coordination
    description: >-
      Manages task queues, statuses and scheduled operations (cron jobs).
      Utilises cheap models to minimise cost for routine coordination tasks.
    default_tier: cheap
    memory: global

  prompt_builder:
    role: Prompt‑Builder
    description: >-
      Writes and audits prompt files under the `prompts/` directory.  Maintains
      best practices and version control of all agent system prompts.
    default_tier: standard
    memory: prompt_kb

  model_selector:
    role: Model‑Selector
    description: >-
      Tracks model performance and pricing.  Reads ratings from external
      services such as OpenRouter or Yandex and decides which model to use.
    default_tier: cheap
    memory: models_kb

  agent_builder:
    role: Agent‑Builder
    description: >-
      Creates new agents based on specifications.  Uses the `build_from_spec`
      function to extend the system dynamically.
    default_tier: cheap
    memory: none

  instance_factory:
    role: Instance‑Factory
    description: >-
      Deploys new MAS instances, either internal or client‑facing.  Writes
      `.env` files and executes `docker compose up -d`.  Registers endpoints in
      Postgres.
    default_tier: cheap
    memory: instances_db

  researcher:
    role: Researcher
    description: >-
      Performs web and API research.  Uses retrieval‑augmented generation
      (RAG) techniques to answer questions.  Utilises premium models for
      high‑quality search results.
    default_tier: premium
    memory: research_mem

  fact_checker:
    role: Fact‑Checker
    description: >-
      Validates sources and information provided by the Researcher.  Ensures
      that generated content meets quality standards.  Relies on cheap
      models for verification tasks.
    default_tier: cheap
    memory: none

  multi_tool:
    role: MultiTool
    description: >-
      Provides access to external APIs via a fixed LLM (e.g. Kimi K2).  Acts as
      a gateway for third‑party services.
    default_tier: fixed
    memory: none

  workflow_builder:
    role: WF‑Builder
    description: >-
      Generates n8n workflow definitions in JSON format from high‑level
      specifications.  Uses standard models to balance cost and quality.
    default_tier: standard
    memory: wf_recipes

  webapp_builder:
    role: WebApp‑Builder
    description: >-
      Interfaces with GPT‑Pilot to generate web applications from JSON
      specifications.  Upgrades to premium models when higher quality is
      required.
    default_tier: standard
    memory: apps_mem

  communicator:
    role: Communicator
    description: >-
      Handles interaction with the user via Telegram.  Converts speech to text
      (STT) and text to speech (TTS) using Yandex SpeechKit.  Maintains
      conversation memory.
    default_tier: fixed
    memory: chat_mem