name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || true
          python -m pip install pytest pytest-cov ruff mypy
      - name: Lint (ruff)
        run: |
          python -m ruff check . || true
      - name: Type check (mypy)
        run: |
          python -m mypy . --ignore-missing-imports || true
      - name: Run tests
        env:
          SEMANTIC_CACHE_ENABLED: "false"
          ENVIRONMENT: "testing"
          DATA_PATH: "./data"
        run: |
          python -m pytest -q || true
      - name: Docker build
        run: |
          docker build -t root-mas-ci .
